//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moteur
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_erreur
    {
        public int Cle { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
    }
}
